/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz.tech.gui;

import java.awt.Color;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import quiz.tech.dao.PerformanceDao;
import quiz.tech.entities.Performance;
import quiz.tech.utils.UserProfile;

/**
 *
 * @author spsub
 */
public class ViewAllStudentsScoreFrame extends javax.swing.JFrame {

	/**
	 * Creates new form ViewAllStudentsScoreFrame
	 */
	private Color oldColor;

	public ViewAllStudentsScoreFrame() {
		initComponents();
		setLocationRelativeTo(null);
		lblShowName.setText("Hello " + UserProfile.getUserName());
		oldColor = lblLogout.getForeground();
		showPerformers();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		lblShowName = new javax.swing.JLabel();
		lblLogout = new javax.swing.JLabel();
		myPanel = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jtStudentData = new javax.swing.JTable();
		btnBack = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Tech Quiz App");

		jPanel1.setBackground(new java.awt.Color(0, 0, 0));

		jLabel1.setBackground(new java.awt.Color(0, 0, 0));
		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(153, 255, 153));
		jLabel1.setText("All Students Score Panel");

		lblShowName.setBackground(new java.awt.Color(0, 0, 0));
		lblShowName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
		lblShowName.setForeground(new java.awt.Color(102, 255, 102));

		lblLogout.setBackground(new java.awt.Color(0, 0, 0));
		lblLogout.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
		lblLogout.setForeground(new java.awt.Color(102, 255, 102));
		lblLogout.setText("Logout");
		lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				lblLogoutMouseClicked(evt);
			}

			public void mouseEntered(java.awt.event.MouseEvent evt) {
				lblLogoutMouseEntered(evt);
			}

			public void mouseExited(java.awt.event.MouseEvent evt) {
				lblLogoutMouseExited(evt);
			}
		});

		myPanel.setBackground(new java.awt.Color(0, 0, 0));
		myPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "All Student Score Details",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(153, 255, 153))); // NOI18N

		jtStudentData.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "UserID", "ExamID", "Right", "Wrong", "Unattemped", "Percentage", "Subject" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false, false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane2.setViewportView(jtStudentData);

		btnBack.setBackground(new java.awt.Color(0, 0, 0));
		btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		btnBack.setForeground(new java.awt.Color(153, 255, 153));
		btnBack.setText("Back");
		btnBack.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBackActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout myPanelLayout = new javax.swing.GroupLayout(myPanel);
		myPanel.setLayout(myPanelLayout);
		myPanelLayout.setHorizontalGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(myPanelLayout.createSequentialGroup().addGap(165, 165, 165)
						.addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 213,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE));
		myPanelLayout.setVerticalGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(myPanelLayout.createSequentialGroup()
						.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(41, 41, 41).addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(27, 27, 27)));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(148, 148, 148)
										.addComponent(jLabel1))
								.addComponent(lblShowName, javax.swing.GroupLayout.PREFERRED_SIZE, 151,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 67,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addComponent(myPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel1Layout.createSequentialGroup()
												.addComponent(lblShowName, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(3, 3, 3).addComponent(jLabel1,
														javax.swing.GroupLayout.PREFERRED_SIZE, 30,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(90, 90, 90).addComponent(myPanel,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		myPanel.getAccessibleContext().setAccessibleName("Student Score Details");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lblLogoutMouseClicked
		LoginFrame loginFrame = new LoginFrame();
		loginFrame.setVisible(true);
		this.dispose();
	}// GEN-LAST:event_lblLogoutMouseClicked

	private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lblLogoutMouseEntered
		lblLogout.setForeground(Color.white);
	}// GEN-LAST:event_lblLogoutMouseEntered

	private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lblLogoutMouseExited
		lblLogout.setForeground(oldColor);
	}// GEN-LAST:event_lblLogoutMouseExited

	private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBackActionPerformed
		// TODO add your handling code here:
		ViewScoresFrame viewScoresFrame = new ViewScoresFrame();
		viewScoresFrame.setVisible(true);
		this.dispose();
	}// GEN-LAST:event_btnBackActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ViewAllStudentsScoreFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ViewAllStudentsScoreFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ViewAllStudentsScoreFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ViewAllStudentsScoreFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ViewAllStudentsScoreFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnBack;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTable jtStudentData;
	private javax.swing.JLabel lblLogout;
	private javax.swing.JLabel lblShowName;
	private javax.swing.JPanel myPanel;
	// End of variables declaration//GEN-END:variables

	private void showPerformers() {
		List<Performance> performers = PerformanceDao.getAllPerformers();

		if (performers.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Sorry! No student appeared to this paper yet.","Notification",JOptionPane.INFORMATION_MESSAGE);
			System.out.println("no student appeared in the exam yet.");
			return;
		}

		DefaultTableModel tableModel = (DefaultTableModel) jtStudentData.getModel();
		Object[] row = new Object[7];

		performers.forEach(performer -> {
			row[0] = performer.getUser().getUserId();
			row[1] = performer.getExam().getExamID();
			row[2] = performer.getRight();
			row[3] = performer.getWrong();
			row[4] = performer.getUnattemped();
			row[5] = performer.getPercentage();
			row[6] = performer.getExam().getSubject();
			tableModel.addRow(row);

		});

	}

}
