/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz.tech.gui;

import java.awt.Color;
import java.awt.Frame;
import java.util.Arrays;

import quiz.tech.dao.UserDao;
import quiz.tech.entities.User;
import quiz.tech.utils.UserProfile;

/**
 *
 * @author spsub
 */
public class ChangePasswordFrame extends javax.swing.JFrame {

	/**
	 * Creates new form ChangePasswordFrame
	 */
	private Color oldColor;
	private Frame frame;
	private String oldPassword;
	private User user;

	public ChangePasswordFrame() {
		initComponents();
		this.setLocationRelativeTo(null);
		user = new User();
		user.setUserId(UserProfile.getUserId());
		user.setUserName(UserProfile.getUserName());
		user.setUserType(UserProfile.getUserType());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		txtNewPassword = new javax.swing.JPasswordField();
		jLabel7 = new javax.swing.JLabel();
		txtNewRepoPassword = new javax.swing.JPasswordField();
		lblShowName = new javax.swing.JLabel();
		btnChangePassword = new javax.swing.JButton();
		btnBack = new javax.swing.JButton();
		lblLogout = new javax.swing.JLabel();
		txtOldPassword = new javax.swing.JPasswordField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(0, 0, 0));

		jLabel3.setBackground(new java.awt.Color(0, 0, 0));
		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel3.setForeground(new java.awt.Color(153, 255, 153));
		jLabel3.setText("Change Password Portal");

		jLabel4.setBackground(new java.awt.Color(0, 0, 0));
		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jLabel4.setForeground(new java.awt.Color(153, 255, 153));
		jLabel4.setText("Old Password");

		jLabel6.setBackground(new java.awt.Color(0, 0, 0));
		jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jLabel6.setForeground(new java.awt.Color(153, 255, 153));
		jLabel6.setText("Password");

		txtNewPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

		jLabel7.setBackground(new java.awt.Color(0, 0, 0));
		jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jLabel7.setForeground(new java.awt.Color(153, 255, 153));
		jLabel7.setText("Retype Password");

		txtNewRepoPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

		lblShowName.setBackground(new java.awt.Color(0, 0, 0));
		lblShowName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		lblShowName.setForeground(new java.awt.Color(102, 255, 102));

		btnChangePassword.setBackground(new java.awt.Color(0, 0, 0));
		btnChangePassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		btnChangePassword.setForeground(new java.awt.Color(153, 255, 153));
		btnChangePassword.setText("Save");
		btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnChangePasswordActionPerformed(evt);
			}
		});

		btnBack.setBackground(new java.awt.Color(0, 0, 0));
		btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		btnBack.setForeground(new java.awt.Color(153, 255, 153));
		btnBack.setText("Back");
		btnBack.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBackActionPerformed(evt);
			}
		});

		lblLogout.setBackground(new java.awt.Color(0, 0, 0));
		lblLogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		lblLogout.setForeground(new java.awt.Color(102, 255, 102));
		lblLogout.setText("Logout");
		lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				lblLogoutMouseClicked(evt);
			}

			public void mouseEntered(java.awt.event.MouseEvent evt) {
				lblLogoutMouseEntered(evt);
			}

			public void mouseExited(java.awt.event.MouseEvent evt) {
				lblLogoutMouseExited(evt);
			}
		});

		txtOldPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addComponent(lblShowName, javax.swing.GroupLayout.PREFERRED_SIZE, 146,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 62,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(18, 18, 18).addComponent(jLabel5)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(jPanel1Layout.createSequentialGroup()
																.addGap(24, 24, 24)
																.addComponent(btnChangePassword,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 128,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(51, 51, 51))
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel1Layout.createSequentialGroup().addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(jPanel1Layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(jLabel4,
																						javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(jLabel6,
																						javax.swing.GroupLayout.Alignment.TRAILING))
																		.addGap(48, 48, 48)))
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(txtNewPassword,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 203,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(txtOldPassword,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 203,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
														jPanel1Layout.createSequentialGroup().addComponent(jLabel7)
																.addGap(48, 48, 48).addComponent(txtNewRepoPassword,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 203,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGroup(jPanel1Layout.createSequentialGroup().addGap(255, 255, 255)
												.addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 133,
														javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(84, 84, 84).addComponent(jLabel3)))
						.addGap(0, 39, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(lblLogout, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(lblShowName, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(139, 139, 139).addComponent(
										jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 169,
										javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(18, 18, 18)
										.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(46, 46, 46)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(txtOldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 36,
														Short.MAX_VALUE)
												.addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addGap(18, 18, 18)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel1Layout.createSequentialGroup()
														.addComponent(txtNewPassword,
																javax.swing.GroupLayout.DEFAULT_SIZE, 36,
																Short.MAX_VALUE)
														.addGap(2, 2, 2))
												.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(22, 22, 22)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 36,
														Short.MAX_VALUE)
												.addComponent(txtNewRepoPassword))
										.addGap(29, 29, 29)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(btnChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE,
														47, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
														javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addGap(26, 26, 26)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lblLogoutMouseClicked
		frame = new LoginFrame();
		frame.setVisible(true);
		this.dispose();
	}// GEN-LAST:event_lblLogoutMouseClicked

	private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lblLogoutMouseEntered
		lblLogout.setForeground(Color.white);
	}// GEN-LAST:event_lblLogoutMouseEntered

	private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lblLogoutMouseExited
		lblLogout.setForeground(oldColor);
	}// GEN-LAST:event_lblLogoutMouseExited

	private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnChangePasswordActionPerformed
		if (isNotValidInputs())
			return;
		
		if(! UserDao.updatePassword(user, oldPassword)) {
			System.out.println("no user found with given student id and password");
			return;
		}
		
		System.out.println("password updated successfully.");

	}// GEN-LAST:event_btnChangePasswordActionPerformed

	private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBackActionPerformed

		frame = new StudentOptionFrame();
		frame.setVisible(true);
		this.dispose();

	}// GEN-LAST:event_btnBackActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ChangePasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ChangePasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ChangePasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ChangePasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ChangePasswordFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnChangePassword;
	private javax.swing.JButton btnBack;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JLabel lblLogout;
	private javax.swing.JLabel lblShowName;
	private javax.swing.JPasswordField txtNewPassword;
	private javax.swing.JPasswordField txtNewRepoPassword;
	private javax.swing.JPasswordField txtOldPassword;
	// End of variables declaration//GEN-END:variables

	private boolean isNotValidInputs() {

		if (txtOldPassword.getPassword().length == 0 || txtNewPassword.getPassword().length == 0
				|| txtNewRepoPassword.getPassword().length == 0) {
			
			System.out.println("please fill all the fields");
			return true;
			
		}
		
		
		if(!Arrays.equals(txtNewPassword.getPassword(), txtNewRepoPassword.getPassword())) {
			System.out.println("password didn't match");
			return true;
		}
		
		oldPassword = String.valueOf(txtOldPassword.getPassword());
		user.setPassword(String.valueOf(txtNewPassword.getPassword()));
			
		return false;
	}

}
